# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170730_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarmenu',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='navbarmenu',
            name='link',
        ),
        migrations.AddField(
            model_name='category',
            name='explain',
            field=models.CharField(default='this is body', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='/', max_length=20),
        ),
    ]
